input_stream: 'IMAGE:in_stream'
output_stream: 'TENSORS:out_stream'

node {
  calculator: "ImageToTensorCalculator"
  input_stream: "IMAGE:in_stream"
  output_stream: "TENSORS:image_tensor"

  options {
    [mediapipe.ImageToTensorCalculatorOptions.ext] {
      output_tensor_width: 224
      output_tensor_height: 224
      keep_aspect_ratio: false
      output_tensor_float_range {
        min: -1.0
        max: 1.0
      }
    }
  }
}

node {
  calculator: "InferenceCalculator"
  input_stream: "TENSORS:image_tensor"
  output_stream: "TENSORS:inference_yolo"
  options: {
    [mediapipe.InferenceCalculatorOptions.ext] {
      model_path: "yolov8n_float32.tflite"
      delegate { xnnpack {} }
    }
  }
}

node {
  calculator: "TensorsToFloatsCalculator"
  input_stream: "TENSORS:inference_yolo"
  output_stream: "FLOATS:out_stream"
}